### ISSUE TITLE
ImportError: No module named rest_framework

### ISSUE THREAD

**Issue by RingoHHuang** [MLHale/gazepoint-websockets#7]
Hi @MLHale,

Running `start startserver.bat` gives me `ImportError: No module named rest_framework`. Are there additional dependencies that need to be installed for this to run?

Also, I'm using Windows 10 Home with Python 2.7.9.

Thanks,
Ringo

**Comment by MLHale** [comment]
Hi @RingoHHuang - this should be fixed in latest version of master. I accidentally left a few unused dependencies in the settings.py file.

**Comment by RingoHHuang** [comment]
Thanks @MLHale. I'm now running into `ImportError: No module named picklefield.fields`. Can you check if this is also unused or if it needs to be installed?

**Comment by MLHale** [comment]
@RingoHHuang Thanks! Sorry, I missed this install step. I've added it to the readme.

You should be able to just do ```pip install django-picklefield``` to resolve the issue

**Comment by RingoHHuang** [comment]
Thanks @MLHale. I'm now running into a different issue with the startserver.bat script. I've copied the full traceback here:

```
Unhandled exception in thread started by <function wrapper at 0x04250EB0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\channels\management\commands\runserver.py", line 49, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "C:\Python27\lib\site-packages\channels\asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "C:\Python27\lib\site-packages\channels\asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "C:\Python27\lib\site-packages\channels\asgi.py", line 65, in _make_backend
    routing=routing,
  File "C:\Python27\lib\site-packages\channels\asgi.py", line 97, in __init__
    self.router = Router(self.routing)
  File "C:\Python27\lib\site-packages\channels\routing.py", line 25, in __init__
    self.root = Include(routing)
  File "C:\Python27\lib\site-packages\channels\routing.py", line 201, in __init__
    self.routing = Router.resolve_routing(routing)
  File "C:\Python27\lib\site-packages\channels\routing.py", line 75, in resolve_routing
    raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
django.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'api.routing.channel_routing': No module named lxml.etree
```

**Comment by MLHale** [comment]
Ok, @RingoHHuang let me know if that works.

I just added two more commits - sorry for not having all of the dependencies documented correctly and causing a bunch of back-and-forth. 

Just install the following:
```
pip install django-cors-headers
pip install lxml
```
I added the new install steps into the readme and (I think) cleaned up any other potential dependency issues.

**Comment by RingoHHuang** [comment]
No worries @MLHale!

I'm again encountering `ImportError: No module named rest_framework`. Full traceback:

```
Unhandled exception in thread started by <function wrapper at 0x042C5EB0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\channels\management\commands\runserver.py", line 55, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Ringo\Desktop\eyestream\cybertrustgazepoint\urls.py", line 21, in <module>
    from rest_framework import routers
ImportError: No module named rest_framework
```

**Comment by MLHale** [comment]
@ringohhuang did you pull the latest changes? I think I already removed that line.

**Comment by RingoHHuang** [comment]
Ah that's right, I didn't pull the latest changes.

I am now encountering `ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.` (see below). Can this be because I didn't configure the port forwarding described in your docker installation instructions?

```
2019-09-07 15:17:27,588 - ERROR - server - Error trying to receive messages: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\channels\management\commands\runserver.py", line 176, in run
    worker.run()
  File "C:\Python27\lib\site-packages\channels\worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "C:\Python27\lib\site-packages\asgiref\base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "C:\Python27\lib\site-packages\asgi_redis\core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "C:\Python27\lib\site-packages\redis\client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "C:\Python27\lib\site-packages\redis\client.py", line 673, in execute_command
    connection.send_command(*args)
  File "C:\Python27\lib\site-packages\redis\connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "C:\Python27\lib\site-packages\redis\connection.py", line 585, in send_packed_command
    self.connect()
  File "C:\Python27\lib\site-packages\redis\connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
```

**Comment by MLHale** [comment]
@RingoHHuang - Yeah this error is almost certainly due to port forwarding. This is actually a good sign because it means the server is installed and working, it just cannot reach the redis docker container (which should be hosted on localhost:6379 if port forwarding is setup).

**Comment by RingoHHuang** [comment]
Thanks @MLHale - original question has been addressed, and I set up the port forwarding configurations. Closing this issue.
