### ISSUE TITLE
Port Forwarding Instructions

### ISSUE THREAD

**Issue by RingoHHuang** [MLHale/gazepoint-websockets#9]
Hi @MLHale,

I'm encountering a connection problem when running the startserver.bat script. Below is the full log output:

```
Performing system checks...

System check identified some issues:

WARNINGS:
api.EyeTrackerSession.args: (picklefield.E001) PickledObjectField default should be a callable instead of a mutable instance so that it's not shared between all field instances.
        HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 1 issue (0 silenced).
September 12, 2019 - 17:15:23
Django version 1.11.23, using settings 'cybertrustgazepoint.settings'
Starting Channels development server at http://127.0.0.1:8888/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CTRL-BREAK.
2019-09-12 17:15:23,500 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-12 17:15:23,500 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-12 17:15:23,503 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-12 17:15:23,503 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-12 17:15:23,506 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-09-12 17:15:23,506 - INFO - server - Using busy-loop synchronous mode on channel layer
2019-09-12 17:15:23,506 - INFO - server - Listening on endpoint tcp:port=8888:interface=127.0.0.1
2019-09-12 17:15:27,529 - ERROR - server - Error trying to receive messages: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\channels\management\commands\runserver.py", line 176, in run
    worker.run()
  File "C:\Python27\lib\site-packages\channels\worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "C:\Python27\lib\site-packages\asgiref\base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "C:\Python27\lib\site-packages\asgi_redis\core.py", line 168, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "C:\Python27\lib\site-packages\redis\client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "C:\Python27\lib\site-packages\redis\client.py", line 673, in execute_command
    connection.send_command(*args)
  File "C:\Python27\lib\site-packages\redis\connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "C:\Python27\lib\site-packages\redis\connection.py", line 585, in send_packed_command
    self.connect()
  File "C:\Python27\lib\site-packages\redis\connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
```
I don't know if I'm following the port forwarding instructions correctly. Can you please check for any errors in the attached image?

![port_forwarding](https://user-images.githubusercontent.com/20446454/64829475-53817000-d581-11e9-9f2a-5b9a166ca19d.PNG)

**Comment by MLHale** [comment]
Hi @RingoHHuang - The image you have looks correct. Are you performing all CLI interactions in the docker toolbox terminal? Since you don't have docker community edition, only the docker toolbox bash shell is setup correctly to work with docker containers. 

You should use it to launch startserver.bat.

If you try that and it is not working, I would suggest you delete the VM that docker creates automatically for you in virtual box and then relaunch the docker toolbox bash shell. This should re-create the VM and fix any misconfiguration (if it exists). At that point you can double check the port forwarding is still correct and then try launching the script again.

**Comment by MLHale** [comment]
The other thing to look at is the running docker containers - to verify that the redis image container is running.

```
docker ps -a
```

It could be an issue since you were trying to run it before before you added the port forwarding configuration, so perhaps the container never was shut down.

**Comment by RingoHHuang** [comment]
Hi @MLHale,

I think that was my problem - I wasn't using the docker toolbox terminal. I now get this: 
```
Performing system checks...

System check identified some issues:

WARNINGS:
api.EyeTrackerSession.args: (picklefield.E001) PickledObjectField default should be a callable instead of a mutable instance so that it's not shared between all field instances.
        HINT: Use a callable instead, e.g., use `list` instead of `[]`.

System check identified 1 issue (0 silenced).
September 13, 2019 - 12:26:19
Django version 1.11.23, using settings 'cybertrustgazepoint.settings'
Starting Channels development server at http://127.0.0.1:8888/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CTRL-BREAK.
2019-09-13 12:26:19,733 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-13 12:26:19,734 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-13 12:26:19,742 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-13 12:26:19,743 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2019-09-13 12:26:19,746 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-09-13 12:26:19,746 - INFO - server - Using busy-loop synchronous mode on channel layer
2019-09-13 12:26:19,746 - INFO - server - Listening on endpoint tcp:port=8888:interface=127.0.0.1
```
As someone who has zero experience with docker (and perhaps, speaking on behalf of future gazepoint users with a similar lack of experience), I think it would be helpful to add that the startserver.bat script should be run on the docker terminal (if using Windows Home Edition) and include any additional intermediary step, however basic, that you think can go in the "Getting Started" and "Basic Manual Testing" sections.

Thanks!

**Comment by MLHale** [comment]
@RingoHHuang - Thanks for the feedback - I will clarify that language in the instructions

**Comment by RingoHHuang** [comment]
Thanks for the addition, @MLHale!
